### ISSUE TITLE
Opening a saved stockpile gives a "Cannot find central directory" error popup.

### ISSUE THREAD

**Issue by KingWormo** [ircluzar/RTC#5]
The first time I ran RTC 300 i didn't have any issues (other than that OBS doesn't like attached mode).
I tried prepping the corrupter again for today and I couldn't load my stockpile that I saved the day before.
I've tried deleting/reinstalling, turning off Avast and adding it/the VERSIONS folder as exceptions, and I tried running it all forcing admin rights... I don't get whats going on, seeing as reinstalling the older versions usually fixed it for me (on the rare occasions that it happened).

Here's the error dump, if anyone wants to see it:

************** Exception Text **************
ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(Stream stream)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at BizHawk.Client.EmuHawk.FastZipClass.Run(String[] args) in C:\Users\philt\Documents\PROJECTS\RTC3\Real-Time Corruptor\BizHawk_RTC\BizHawk.Client.EmuHawk\RTC\FastZipProgram.cs:line 365
   at RTC.Stockpile.Extract(String Filename, String Folder, String MasterFile) in C:\Users\philt\Documents\PROJECTS\RTC3\Real-Time Corruptor\BizHawk_RTC\BizHawk.Client.EmuHawk\RTC\RTC_Objects.cs:line 340
   at RTC.Stockpile.Load(DataGridView dgvStockpile, String Filename) in C:\Users\philt\Documents\PROJECTS\RTC3\Real-Time Corruptor\BizHawk_RTC\BizHawk.Client.EmuHawk\RTC\RTC_Objects.cs:line 215
   at RTC.RTC_GH_Form.<btnLoadStockpile_Click>b__31_0(Object ob, EventArgs ev) in C:\Users\philt\Documents\PROJECTS\RTC3\Real-Time Corruptor\BizHawk_RTC\BizHawk.Client.EmuHawk\RTC\RTC_GH_Form.cs:line 627
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ircluzar** [comment]
if you are running it in admin monde, don't do that. this causes the
program to think you execufed it from system32. also old stockpiles wont
work in 3.00, this is a new format.

**Comment by KingWormo** [comment]
Even if I saved the stockpiles in 300?

**Comment by ircluzar** [comment]
no, stockpiles made in 3.00 should work in 3.00, i dont really understand
how that kind of issue can happen unless your stockpile didnt save
properly. are you starting the whole thing from fhe launcher?

On Sep 27, 2017 11:51 PM, "KingWormo" <notifications@github.com> wrote:

Even if I saved the stockpiles in 300?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ircluzar/RTC/issues/5#issuecomment-332720309>, or mute
the thread

**Comment by KingWormo** [comment]
I'm trying both the launcher and the start.bat

**Comment by ircluzar** [comment]
well, i have no idea what's happenning on your machine right now, none of
our testers have reported that kind of issue. try to get the zip version on
redscientist.com, maybe your computer doesn't like the new launcher.
otherwise, you can wait for another version to come out, we're already
working on a big update for v3.

**Comment by KingWormo** [comment]
well it happened before 3.00, so idk :b

**Comment by ircluzar** [comment]
I'm closing the RTC repo, issues should be opened in the RTC3 repo now.
You can also come discuss with us at http://discord.corrupt.wiki
